int errprint(char *level, char *routine, char *error);
int bitcnt(int x);
void advance_reg(int *reg_fill);
int get_fill_int(const int *n, int *r0);
int get_fill_flt(const int *n, float *r0);
int get_fill_dbl(const int *n, double *r0);
void si_double_int(int *a, const int *b);
void si_double_flt(int *a, int *b);
void si_double_dbl(int *a, int *b);
int get_rn_int(int *genptr);
float get_rn_flt(int *genptr);
double get_rn_dbl(int *genptr);
int **initialize_int(int ngen, int length, int seed, const int *nstart);
int **initialize_flt(int ngen, int length, int seed, int *nstart);
int **initialize_dbl(int ngen, int length, int seed, int *nstart);
int *init_rng_d_int(int gennum, int length, int seed, int total_gen);
int *init_rng_d_flt(int gennum, int length, int seed, int total_gen);
int *init_rng_d_dbl(int gennum, int length, int seed, int total_gen);
int **init_rng_s_int(int ngen, int length, int seed);
int **init_rng_s_flt(int ngen, int length, int seed);
int **init_rng_s_dbl(int ngen, int length, int seed);
int **spawn_rng_int(int *genptr, int nspawned);
int **spawn_rng_flt(int *genptr, int nspawned);
int **spawn_rng_dbl(int *genptr, int nspawned);
int get_llag_rng(void);
int get_klag_rng(void);
int get_seed_rng(void);
int get_hptr_rng_int(const int *genptr);
int get_hptr_rng_flt(const int *genptr);
int get_hptr_rng_dbl(const int *genptr);
int *get_fill_rng_int(const int *genptr);
float *get_fill_rng_flt(const int *genptr);
double *get_fill_rng_dbl(const int *genptr);
int *get_next_index_rng_int(const int *genptr);
int *get_next_index_rng_flt(const int *genptr);
int *get_next_index_rng_dbl(const int *genptr);
void si_halve_int(int *a);
void si_halve_flt(int *a);
void si_halve_dbl(int *a);
int *get_node_index_rng_int(const int *genptr);
int *get_node_index_rng_flt(const int *genptr);
int *get_node_index_rng_dbl(const int *genptr);
char *pack_rng_int(int *genptr, int *size);
char *pack_rng_flt(int *genptr, int *size);
char *pack_rng_dbl(int *genptr, int *size);
int *unpack_rng_int(char *packed);
int *unpack_rng_flt(char *packed);
int *unpack_rng_dbl(char *packed);
void free_rng_int(int *genptr);
void free_rng_flt(int *genptr);
void free_rng_dbl(int *genptr);
